### GET request to example server
POST localhost:8080/diary?date=2024-05-31
Content-Type: application/json

감사합니다1

###

GET localhost:8080/diary?date=2024-05-31

###

GET localhost:8080/diary/between?startDate=2024-05-30&endDate=2024-05-31

###

PUT localhost:8080/diary?date=2024-05-31
Content-Type: application/json

새로운 일기입니다

###
DELETE localhost:8080/diary?date=2024-05-31
Content-Type: application/json
